config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'heads#index'

  get 'og' => 'head_images#og_images'

  resources :heads

  resources :demos

  get '/:id' => 'heads#show'
  get 'samples/:sample_id' => 'heads#show'

  get 'head_og_image/:id' => 'head_images#head_og_image', as: :head_og_image
  get 'head_image/:id' => 'head_images#head_image', as: :head_image
  get 'head_background_image/:id' => 'head_images#head_background_image', as: :head_background_image

  put 'head_og_image/:id' => 'head_images#update', as: :update_head_og_image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/png_decoder.rb
module PngDecoder

  PREFIX = 'data:image/png;base64,'

  def decode_png(data_url)
    return unless data_url
    Base64.decode64(data_url[PREFIX.length .. -1])
  end

end

app/models/head.rb
class Head < ApplicationRecord
  validates_presence_of :data_url
  validate :all_valid_data_urls

  DEFAULT_HEADS = %w(bern cage hill locke)
  include PngDecoder

  def self.random_default
    where(external_id: DEFAULT_HEADS).to_a.sample
  end

  before_create :set_external_id

  def to_blob
    decode_png(data_url)
  end

  def background_to_blob
    decode_png(background_data_url)
  end

  def og_to_blob
    decode_png(og_data_url)
  end

  def get_options
    JSON.parse(options || '{}')
  end

  def options_as_query
    get_options.to_query
  end

  def body_options_as_query
    get_options.slice('hat', 'feet', 'hands').to_query
  end

  private

  def set_external_id
    my_random_external_id = random_external_id
    return set_external_id if Head.where(external_id: my_random_external_id).exists?
    self.external_id = my_random_external_id
  end

  def random_external_id
    "#{rand_chars(2)}#{rand_num}#{rand_chars(2)}"
  end

  def rand_num
    rand(10)
  end

  def rand_chars(length)
    SecureRandom.base58(length)
  end

  def all_valid_data_urls
    return if [data_url, background_data_url, og_data_url].all? { |s| valid_data_url?(s) }
    errors.add(:base, 'not valid data_url')
  end

  def valid_data_url?(val)
    return true unless val.present?
    val.starts_with?("data:image/png;base64,")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController

  before_filter :find_head_and_external_id

  def index
    set_ivars
    render :index, layout: 'demo'
  end

  def show
    render params[:id], layout: 'demo'
  end

  private

  def find_head_and_external_id
    @external_id = params[:head]
    @head = @external_id ? Head.find_by_external_id(@external_id) : Head.random_default
    @head_id_message = head_id_message.html_safe
  end

  def set_ivars
    @easy_setup = render_html_string('easy_setup')
    @master_setup = render_html_string('master_setup')
    @advanced_js = render_js_string('advanced_setup')
    @opacity_js = render_js_string('opacity')
    @opacity_init_js = render_js_string('opacity_init')
    @other_parent_js = render_js_string('other_parent')
    @multi_heads_js = render_js_string('multi_heads')
    @head_id_message = head_id_message
  end

  def head_id_message
    if @external_id
      "'#{@external_id}' is your head's id"
    else
      "replace '#{@head.external_id}' with your head's id"
    end
  end

  def render_html_string(name)
    render_escaped_string(name, 'html')
  end

  def render_js_string(name)
    render_escaped_string(name, 'js')
  end

  def render_escaped_string(name, type)
    str = render_to_string("demos/js/#{name}.#{type}.erb", layout: nil)
    CGI.escapeHTML(str).html_safe
  end

end

app/controllers/embed_controller.rb
class EmbedController < ApplicationController

  def info
    @external_id = params[:id]
    @head = @external_id ? Head.find_by_external_id(@external_id) : Head.random_default
    @easy_setup = easy_setup
    @master_setup = init_script_tag
    @advanced_js = advanced_js
  end

  private

  def easy_setup
    tag = <<-HTML
    #{init_script_tag}<script>#{easy_setup_js}</script>
    HTML

    tag.chomp
  end

  def easy_setup_js
    <<-JAVASCRIPT
    document.addEventListener("DOMContentLoaded",function(){(new Friendheads('#{@head.external_id}')).add();});
    JAVASCRIPT
  end

  def init_script_tag
    <<-HTML
    <script src="http://www.friendheads.com/js/embed.js"></script>
    HTML
  end

  def advanced_js
    <<-JAVASCRIPT
      var friendheads = new Friendheads('#{@head.external_id}');

      friendheads.add(); // add one head
      friendheads.add(7); // add 7 head
      friendheads.add(-2); // remove 2 heads

      friendheads.count(); // get head count
      friendheads.count(5); // set head count

      friendheads.destroy(); // remove instance from dom
    JAVASCRIPT
  end

end

app/controllers/head_images_controller.rb
class HeadImagesController < ApplicationController
  before_filter :find_head

  def head_og_image
    if @head.og_to_blob
      send_data @head.og_to_blob, type: 'image/png', disposition: 'inline'
    else
      redirect_to '/images/og_image.png'
    end
  end

  def update
    unless @head.og_data_url
      @head.update_attribute(:og_data_url, params[:og_image])
    end
    head(:ok)
  end

  def head_image
    send_data @head.to_blob, :type => 'image/png',:disposition => 'inline'
  end

  def head_background_image
    @head = Head.find_by_external_id(params[:id])
    blob = @head.background_to_blob
    if blob
      send_data blob, :type => 'image/png',:disposition => 'inline'
    else
      head :ok
    end
  end

  def og_images
    @ids = Head.all.order(created_at: :desc).pluck(:external_id)
    render 'og'
  end

  private

  def find_head
    @head = Head.find_by_external_id(params[:id])
  end
end

app/controllers/heads_controller.rb
class HeadsController < ApplicationController
  def index
    @head = Head.random_default
  end

  def show
    @embedded = !!params[:embedded]
    @head = Head.find_by(external_id: params[:id])
    return if @head

    if @embedded
      @head = Head.find(external_id: '_404_')
    else
      raise ActionController::RoutingError.new(404)
    end
  end

  def create
    h = Head.create!(head_params)
    render json: {id: h.external_id}
  end

  private

  def head_params
    params.require(:head).permit(:data_url, :background_data_url, :options)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heads_helper.rb
module HeadsHelper
end

app/views/demos/1.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Embed example</title>
    <script src="/js/embed.js"></script>
    <script>document.addEventListener("DOMContentLoaded",function(){(new Friendheads('<%= @head.external_id %>')).add();});</script>
  </head>
  <body>
    <br><br>
    <center>
      blah blah lorem ipsum so great blah blah so minimal blah checkout this friendhead
    </center>
  </body>
</html>

app/views/demos/2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Embed example</title>
    <script src="/js/embed.js"></script>
  </head>
  <body>
    <br><br>
    <center>
      blah blah lorem ipsum so great look at this

      <br><br>
      <button onclick='friendheads.add()'>Add head</button>
      <br><br>
      <button onclick='friendheads.add(-1)'>Remove head</button>
      <br><br>
      <input type="range" min='0' max='10' value='0' onchange='friendheads.count(this.value)'>
      <br><br>

      omg isn't this great
    </center>

    <script>
      var friendheads = new Friendheads('<%= @head.external_id %>');
    </script>
  </body>
</html>

app/views/demos/3.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Embed example</title>
    <script src="/js/embed.js"></script>
  </head>
  <body>
    <br><br>
    <center>

      <div style='border: 1px solid red;'>
        This friendheads instance has no container so it will fill the body
        <br><br>
        <button onclick='ariHeads.add(3)'>Add some ariHeads</button>
        <br><br>
        <button onclick='ariHeads.add(-3)'>Remove some ariHeads</button>
        <br><br>
        <label>
          Opacity
          <input type="range" min='0' max='1' step='.1' onchange='ariHeads.opacity(this.value)' value='1'>
        </label>
        <br><br>
      </div>
      <br>
      <div style='border: 1px solid red; position: relative;' id='my-container'>
        This friendheads instance lives inside this <b>relatively positioned</b> container
        <br><br>
        <button onclick='meHeads.add(3)'>Add some meHeads</button>
        <br><br>
        <button onclick='meHeads.add(-3)'>Remove some meHeads</button>
        <br><br>
        <label>
          Opacity
          <input type="range" min='0' max='1' step='.1' onchange='meHeads.opacity(this.value)' value='.8'>
        </label>
        <br><br>
      </div>

    </center>

    <script>
      var ariHeads = new Friendheads('ari');

      var container = document.getElementById('my-container');
      var meHeads = new Friendheads('<%= @head.external_id %>', {opacity: .8, container: container});
    </script>
  </body>
</html>

app/views/demos/index.html.erb
<div class="embed-page center">

  <link rel="stylesheet" href="/vendor/highlight.min.css">
  <script src="/vendor/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>

  <div class="demos-header">
    <div class="link-to-root">
      <%= link_to 'Friendheads', '/' %>
    </div>

    <% if @external_id %>
      <div class="link-to-head">

        <%= link_to "/#{@external_id}" do %>
          <%= image_tag head_image_url(@external_id) %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="post-demos-header"></div>

  <h1>Embedding friendheads</h1>

  <h3>Simple config</h3>

  <div class="big-info">
    To add a friendhead automatically to your page, just add these script tags:
  </div>

  <pre><code class='html'><%= @easy_setup %></code></pre>

  <div class="small-info">
    <% unless @external_id %>
      <%= @head_id_message %>
    <% end %>
  </div>

  <%= link_to('View demo', demo_path({id: 1, head: @external_id}.compact)) %>
  <br><br>

  <h3>Advanced config</h3>


  <div class="big-info">
    Just add the single script tag
  </div>

  <pre><code class='html'><%= @master_setup %></code></pre>

  <div class="big-info">
    Then add and remove your heads later with js
  </div>

  <pre><code class='javascript'><%= @advanced_js %></code></pre>

  <%= link_to('View demo', demo_path({id: 2, head: @external_id}.compact)) %>
  <br><br>

  <h3>More advanced config</h3>

  <div class="big-info">
    You can easily get and set the opacity of the heads
  </div>

  <pre><code class='javascript'><%= @opacity_js %></code></pre>

  <div class="big-info">
    Or initialize with an opacity
  </div>

  <pre><code class='javascript'><%= @opacity_init_js %></code></pre>

  <div class="big-info">
    Add heads to a node other than the body
  </div>

  <pre><code class='javascript'><%= @other_parent_js %></code></pre>

  <div class="big-info">
    Of course there is nothing stopping you from having many friendheads at once
  </div>

  <pre><code class='javascript'><%= @multi_heads_js %></code></pre>

  <%= link_to('View demo', demo_path({id: 3, head: @external_id}.compact)) %>
  <br><br>

  <script src="/js/embed.js"></script>
  <script>
    (new Friendheads('<%= @head.external_id %>')).add();
  </script>
</div>

app/views/demos/js/advanced_setup.js.erb
var friendheads = new Friendheads('<%= @head.external_id %>'); // <%= @head_id_message %>

friendheads.add(); // add one head
friendheads.add(7); // add 7 head
friendheads.add(-2); // remove 2 heads

friendheads.count(); // get head count
friendheads.count(5); // set head count

friendheads.destroy(); // remove instance from dom

app/views/demos/js/easy_setup.html.erb
<script src="http://www.friendheads.com/js/embed.js"></script><script>document.addEventListener("DOMContentLoaded",function(){(new Friendheads('<%= @head.external_id %>')).add();})</script>

app/views/demos/js/master_setup.html.erb
<script src="http://www.friendheads.com/js/embed.js"></script>

app/views/demos/js/multi_heads.js.erb
var ariHeads = new Friendheads('ari');
var meHeads = new Friendheads('<%= @head.external_id %>');
ariHeads.add(4);
meHeads.add(4);

app/views/demos/js/opacity.js.erb
friendheads.opacity(); // get opacity
friendheads.opacity(.6); // set opacity (some float from 0 to 1)

app/views/demos/js/opacity_init.js.erb
var options = { opacity: .7 };
var friendheads = new Friendheads('<%= @head.external_id %>', options);

app/views/demos/js/other_parent.js.erb
var element = document.getElementById('my-friendheads-container'); // positioned HTMLElement or jQuery object
var options = { container: element };
var friendheads = new Friendheads('<%= @head.external_id %>', options);

app/views/embed/info.html.erb
<div class="embed-page center">


  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.10.0/styles/default.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.10.0/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>

  <h1>Embedding friendheads</h1>

  <h3>Simple config</h3>

  <div class="big-info">
    To add a friendhead automatically to your page, just add these script tags:
  </div>

  <pre><code class='html'><%= @easy_setup %></code></pre>

  <div class="small-info">
    <% unless @external_id %>
    (replace '<%= @head.external_id %>' with your head's id)
    <% end %>
  </div>

  <a href="/samples/embed.html">View demo</a>

  <br><br>

  <h3>Advanced config</h3>


  <div class="big-info">
    Just add the single script tag
  </div>

  <pre><code class='html'><%= @master_setup %></code></pre>

  <div class="big-info">
    Then add and remove your heads later with js
  </div>

  <pre><code class='javascript'><%= @advanced_js %></code></pre>

  <a href="/samples/embed2.html">View demo</a>


</div>

app/views/head_images/og.html.erb
<% @ids.each do |id| %>
  <%= link_to "/#{id}" do %>
    <%= image_tag("/head_og_image/#{id}") %>
  <% end %>
<% end %>

app/views/heads/_advanced_settings.html.erb
<div class="advanced-settings js-advanced-settings hidden">

  <label for="js-include-feet">Show feet</label>
  <input type="checkbox" name="feet" id='js-include-feet'>
  <br>
  <label for="js-include-hands">Show hands</label>
  <input type="checkbox" name="hands" id='js-include-hands'>
  <div class="hat-selection">
    <% ['party', 'top', 'santa', 'bow', 'spin', 'mex'].each do |hat| %>
      <%= image_tag "hats/#{hat}.png", id: "#{hat}-hat", data: {hat: hat} %>
    <% end %>
  </div>

  <label for="snail-trail">Snail trail</label>
  <input type="range" min='0' max='9' id='snail-trail' name='snail' step='1' value='0'>

  <label for="head-count">Head count</label>
  <input type="range" name="head-count" id='head-count' min='1' max='50'>
  <span class='head-count-value'></span>

  <form class="background-color-area">
    <div class='background-upload-button upload-button'>Background Image</div>
    <span class='remove-background js-remove-background hidden'>X</span>
  </form>

  <br>
  <button class='big-submit js-submit-form disabled hidden' disabled="disabled">Go</button>
</div>

app/views/heads/_footer.html.erb
<div class="footer clearfix">
  <% if params[:action] == 'show' %>
    <div class="embed">
      <a href='<%= demos_path(head: @head.external_id) %>' target="_blank">
        <%= image_tag 'embed.png' %>
      </a>
    </div>
  <% end %>

  <div class="social">
    <img src="/images/facebook.png" alt="facebook" class='js-facebook-share'>
    <a target="_blank" class='js-twitter-share-anchor'>
      <img src="/images/twitter.png" alt="twitter" class='js-twitter-share'>
    </a>
  </div>
</div>

app/views/heads/_head.html.erb
<div class="header">
  <div class="header-content">
    <div class='header-left'><a href="/">Friendheads</a></div>
    <div class='header-right js-control-buttons'>
      <span class='space-bar-area'><img src="/images/space.png" alt="space-bar" class='js-space-button space-bar'></span>
      <img src="/images/minus.png" alt="-" class='js-minus-button plus-or-minus'>
      <img src="/images/plus.png" alt="+" class='js-plus-button plus-or-minus'>
      <img src="/images/question.png" alt="?" class='js-question-button plus-or-minus'>
      <img src="/images/left.png" alt="left" class='js-left-button left-or-right arrow'>
      <div class="up-and-down">
        <img src="/images/up.png" alt="up" class='js-up-button arrow'>
        <img src="/images/down.png" alt="down" class='js-down-button arrow'>
      </div>
      <img src="/images/right.png" alt="right" class='js-right-button left-or-right arrow'>
    </div>
  </div>
</div>

app/views/heads/_image_preview.html.erb
<div class="img-preview-container-container-hover-area hidden hovered">
  <div class="img-preview-container-container pull-left">
    <div class="img-preview-container">
      <img id='temp-img'>
      <button id='crop-circle'>cricle</button>
      <button id='crop-square'>square</button>
      <button id='crop-none'>No crop</button>
    </div>
  </div>
</div>

app/views/heads/_main.html.erb
<%= content_for :head do %>
  <meta charset="utf-8">

  <script src='/vendor/underscore-min.js'></script>
  <script src='/vendor/dropzone.js' type='text/javascript'></script>
  <script src='/vendor/spectrum.js' type='text/javascript'></script>
  <script src='/vendor/croppie.min.js' type='text/javascript'></script>

  <link rel="stylesheet" href="/vendor/spectrum.css">
  <link rel="stylesheet" href="/vendor/croppie.min.css">

  <title>Friend heads SHOW</title>

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="Friendheads" />
  <meta property="og:site_name" content="Friendheads"/>
  <meta property="og:title" content="Friendheads"/>
  <meta property="og:description" content="For your friends and their heads."/>
  <meta property="og:url" content="<%= request.original_url %>"/>
  <meta name="twitter:description" content="For your friends and their heads."/>
<% end %>

<% if action_name == 'index' %>
  <% options = @head.body_options_as_query %>
<% else %>
  <% options = @head.options_as_query %>
<% end %>

<div id='head-options' data-options='<%= options %>'></div>

<img id='img' class='hidden' src='<%=head_image_path(@head.external_id) %>'>

<div class="hidden js-page-data" data-i='<%= "#{params[:id]}" %>' data-si='<%= "#{params[:sample_id]}" %>'></div>

<% if @embedded %>
  <div id='embebed-iframe'></div>
<% elsif action_name == 'show' %>
  <%= render 'head' %>
<% end %>

<div class="js-form-stuff form-stuff hidden center clearfix">
  <div class='page-title'>Friendheads</div>
  <div class='page-description'>For your friends and their heads</div>

  <%= render 'image_preview' %>

  <div class='image-upload-button upload-button'>Upload/Drop an image</div>
  <span class='js-advanced-settings-toggle extra-option advanced-settings-toggle'>Advanced Settings</span>
  <span class='js-samples-toggle extra-option samples-toggle'>Samples</span>
  <br>

  <div class="js-samples hidden head-samples">
    <% Head::DEFAULT_HEADS.each do |h| %>
      <a href='/<%= h %>' target="_blank" class='sample-link'>
        <%= image_tag "heads/#{h}.png" %>
      </a>
    <% end %>
  </div>

  <%= render 'advanced_settings' %>
</div>
<canvas id="background-canvas" class='hidden'></canvas>
<canvas id="js-content"></canvas>

<%= image_tag "limbs/left.png", class: 'hidden', id: 'left-hand' %>
<%= image_tag "limbs/right.png", class: 'hidden', id: 'right-hand' %>
<%= image_tag "limbs/left-foot.png", class: 'hidden', id: 'left-foot' %>
<%= image_tag "limbs/right-foot.png", class: 'hidden', id: 'right-foot' %>

<% unless @embedded %>
  <%= render 'footer' %>
<% end %>

app/views/heads/index.html.erb
<div id='index-page'>
  <img id='background' class='hidden'>
  <%= render partial: 'main' %>
  <canvas id="resize-canvas" class='hidden'></canvas>

  <div class="big-loading hidden">
    <%= image_tag 'load.gif' %>
  </div>
</div>

<% content_for :head do %>
  <link rel="icon" href="/images/icon.png" id='fav-icon'>
  <meta property="og:image:type" content="image/png" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image" content="http://friendheads.herokuapp.com/images/og_image.png">
<% end %>

app/views/heads/show.html.erb
<% content_for :head do %>
  <meta property="og:image:type" content="image/png" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />

  <% og_image_url = head_og_image_url(@head.external_id, format: 'png') %>

  <meta property="og:image" content="<%= og_image_url %>">
  <meta name="twitter:image" content="<%= og_image_url %>">
  <link rel="icon" href='<%= head_image_url(@head.external_id) %>' id='fav-icon'>

<% end %>

<div id='show-page'>
  <% if @head.background_data_url.present? && !@embedded%>
    <img id='background' src='<%=head_background_image_path(@head.external_id) %>'>
  <% else %>
    <img id='background'>
  <% end %>
  <%= render partial: 'main' %>

  <% unless @head.og_data_url %>
    <canvas id="icon-canvas" data-path='<%= update_head_og_image_path(@head.external_id) %>' class='hidden' width='1200' height="630"></canvas>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendheads</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>
  </head>

  <body class='<%= "#{controller_name}-#{action_name}" %>'>
    <%= yield %>
  </body>
</html>

app/views/layouts/demo.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendheads</title>

    <%= stylesheet_link_tag 'demos', media: 'all' %>
  </head>

  <body class='<%= "#{controller_name}-#{action_name}" %>'>
    <%= yield %>
  </body>

  <% if action_name == 'show' %>
    <br><br>
    <center>
      <%= link_to('Back to demos', demos_path({head: @external_id}.compact)) %>
      <br><br>
      <%= link_to 'Back to Friendheads', '/' %>
    </center>
  <% end %>
</html>